apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: 00000000-0000-0000-0000-000000000000
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: auth.opus.codesio.com
        service: http://keycloak-service.auth.svc.cluster.local:8080
      - hostname: opus.codesio.com
        path: /api/*
        service: http://backend.app.svc.cluster.local:8080
      - hostname: opus.codesio.com
        service: http://frontend.app.svc.cluster.local:8080
      - service: http_status:404
