apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: magnum-opus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/danceavlad/codesio-magnum-opus/frontend:0f14bcaf228e48cfe7748a34e51e6a56c0da9034
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: runtime-config
              mountPath: /usr/share/nginx/html/config/runtime-config.json
              subPath: runtime-config.json
              readOnly: true
      volumes:
        - name: runtime-config
          configMap:
            name: frontend-runtime-config
