resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: backend-config
    namespace: app
    literals:
      - SPRING_PROFILES_ACTIVE=k8s
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-postgres-rw.app.svc.cluster.local:5432/magnum_opus
      - SPRING_DATA_REDIS_HOST=redis.cache.svc.cluster.local
      - SPRING_DATA_REDIS_PORT=6379
      - OAUTH2_ISSUER_URI=https://opus-auth.codesio.com/realms/magnum-opus
generatorOptions:
  disableNameSuffixHash: true
