server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis.cache.svc.cluster.local}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  structured:
    format:
      console: ecs
  level:
    com.codesio.magnum_opus: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
