spring:
  application:
    name: magnum-opus
  modulith:
    detection-strategy: explicitly-annotated

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: never
    info:
      access: read-only
    metrics:
      access: read-only
    prometheus:
      access: read-only
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
